### PR TITLE
feat: added dts file

### PR DESCRIPTION
**Pull request by privatenumber**
🎉 Thanks for sending this pull request! 🎉

Please make sure the title is clear and descriptive.

If you are fixing a typo or documentation, please skip these instructions.

Otherwise please fill in the sections below.

**Which problem is this pull request solving?**

Lack of TypeScript declaration.

**List other issues or pull requests related to this problem**

Fixes https://github.com/ehmicky/get-node/issues/9

**Describe the solution you've chosen**

Based on @ehmicky's commit: https://github.com/ehmicky/fast-cartesian/commit/7cc705b582ad0e26de3be4be5b2e58873e9315e4

**Describe alternatives you've considered**

None

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](../blob/main/CONTRIBUTING.md).
- [x] I have added tests (we are enforcing 100% test coverage).
- [x] I have added documentation in the `README.md`, the `docs` directory (if
      any) and the `examples` directory (if any).
- [ ] The status checks are successful (continuous integration). Those can be
      seen below.

### CODE REVIEW

**Comment by privatenumber** [comment]
Verified working great with:

```sh
# From my fork of get-node
$ npx build-this-branch -c 'npx gulp build'

# From usage codebase
$ pnpm i -D 'privatenumber/get-node#built/dts'
```

**Review by ehmicky — APPROVED** [review]
Thanks a lot @privatenumber!

**Comment by ehmicky** [comment]
This is released in https://github.com/ehmicky/get-node/releases/tag/12.1.0 :tada:

**Comment by privatenumber** [comment]
Thank you @ehmicky !

**Comment by ehmicky** [comment]
Please let me know if the types work for you! 

@all-contributors please add @privatenumber for code, test, ideas

**Pull request merged**
